#General
name: iBank
main: com.iBank.iBank
version: @pomversion@(@build@)[@snap@]{@codename@}
commands:
     bank:
       description: Manage your money
       usage: /bank help
depend: [Vault]
#Generator
description: Banks for iConomy
maintainer: steffengy
authors: [steffengy]
# Add superperms !!
