#General
name: iBank
main: com.iBank.iBank
version: 0.2
commands:
     bank:
       description: Manage your money
       usage: /bank help
depend: [Vault]
#Generator
description: Banks for iConomy
maintainer: steffengy
authors: [steffengy]

