#General
name: iBank
main: com.ibank.iBank
version: ${project.version}
commands:
     bank:
       description: Manage your money
       usage: /bank help
     ibank:
       description: Manage your money
       usage: /ibank help
depend: [Vault]
#Generator
description: Banks for iConomy
maintainer: steffengy
authors: [steffengy]
# Add superperms !!
