#General
name: iBank
main: com.ibank.iBank
version: ${project.version}(${buildNumber})[${version.snap}]
commands:
     bank:
       description: Manage your money
       usage: /bank help
     ibank:
       description: Manage your money
       usage: /ibank help
depend: [Vault]
#Generator
description: Banks
maintainer: steffengy
authors: [steffengy, Trojaner]
# Add superperms !!
